#!/bin/bash

#exit on first error
set -e

BIN_DIR=$(/usr/bin/dirname $0)
DIR=$(/bin/bash -c "cd $BIN_DIR; /bin/pwd")

cd $DIR

# include parse_yaml function
. bash/includes/parse_yaml.sh

CONFIG_FILE=$DIR/bt-build-config.yaml

if [ -f $CONFIG_FILE ]; then
    # read yaml file
    eval $(parse_yaml $CONFIG_FILE "config_")
else
   echo "Config file bt-build-config.yaml does not exist. please copy and edit bt-build-config.yaml.dist from the insfrastructure.dev project"
   exit 1
fi

echo "" | composer install

echo "# This file is auto-generated by the build.sh script in the project root
parameters:
    database_host: null
    database_port: null
    database_name: null
    database_user: null
    database_password: null
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: ThisTokenIsNotSoSecretChangeIt
    api.secret: 2+IExNKEhDCMLqbr+QiP+U76QX+ixQkVzOh9q9MJtUVADSakjouEYu6QEiSAiXHDbgguMqIYg4/74skCXxQBRw==
    beautystack_api_host: $config_api_host
" > $DIR/app/config/parameters.yml

./bin/console cache:clear --env=prod