version: 0.2
phases:
  install:
    commands:
      - npm set registry https://npm.beautystack.xyz
      - echo "//npm.beautystack.xyz/:_authToken=\"CVs2BhIj7A5GJ1ixhNdIkFKkZa5z1uz49EDg+jkDFI4=\"" >> ~/.npmrc
      - echo "always-auth=true" >> ~/.npmrc
      - npm install -g gatsby-cli yarn
      - npm install
  pre_build:
    commands:
      - aws s3 cp s3://beautystack.config/policies/beautystack-privacy-policy.md deploy/markdown/src/beautystack-privacy-policy.md
      - aws s3 cp s3://beautystack.config/policies/beautystack-terms-of-service.md deploy/markdown/src/beautystack-terms-of-service.md
  build:
    commands:
      - chmod +x deploy/markdown/compile.js
      - yarn build
      - mv public build
artifacts:
  files:
    - '**/*'
