#!/bin/bash
set -e

#!/bin/bash

#exit on first error
set -e

BIN_DIR=$(/usr/bin/dirname $0)
DIR=$(/bin/bash -c "cd $BINDIR/..; /bin/pwd")
cd $DIR

a2ensite fe.homepage
source /etc/apache2/envvars
apache2 -DFOREGROUND